name: moxxy_native
description: Interactions with the system for Moxxy
version: 0.1.0
publish_to: https://git.polynom.me/api/packages/Moxxy/pub
homepage: 

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.0
  logging: ^1.2.0
  moxlib:
    hosted: https://git.polynom.me/api/packages/Moxxy/pub
    version: ^0.2.0
  uuid: ^3.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  pigeon: 11.0.1
  very_good_analysis: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: org.moxxy.moxxy_native
        pluginClass: MoxxyNativePlugin
      linux:
        pluginClass: MoxxyNativePlugin
